<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Michael Ferrante">
<meta name="author" content="Jacqueline Adelmann">
<meta name="author" content="Zhuo Cen">
<meta name="author" content="Loren Opbroek">

<title>Effective Presentation Time of a Threat: Testing perception vs.&nbsp;judgment in a modified replication of Abado et al.&nbsp;(2023)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="SG-Analysis_darkmode_files/libs/clipboard/clipboard.min.js"></script>
<script src="SG-Analysis_darkmode_files/libs/quarto-html/quarto.js"></script>
<script src="SG-Analysis_darkmode_files/libs/quarto-html/popper.min.js"></script>
<script src="SG-Analysis_darkmode_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="SG-Analysis_darkmode_files/libs/quarto-html/anchor.min.js"></script>
<link href="SG-Analysis_darkmode_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="SG-Analysis_darkmode_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="SG-Analysis_darkmode_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="SG-Analysis_darkmode_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="SG-Analysis_darkmode_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script src="SG-Analysis_darkmode_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="SG-Analysis_darkmode_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Effective Presentation Time of a Threat: Testing perception vs.&nbsp;judgment in a modified replication of Abado et al.&nbsp;(2023)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Michael Ferrante </p>
             <p>Jacqueline Adelmann </p>
             <p>Zhuo Cen </p>
             <p>Loren Opbroek </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This study aimed to replicate and expand upon Abado et al.’s (2023) finding that adults show an attentional bias, meaning they tend to selectively focus on specific stimuli, toward organically-occurring threats, but not toward threats that are man-made. Similar to the visual discrimination task used in Abado et al., we measured participants’ average speeds in identifying images of organically-occurring (phylogenetic) items and man-made (ontogenetic) items that were either threatening or non-threatening. We also sought to investigate whether Abado et al.’s finding is due to judgment processes rather than the “top-down effect” that our beliefs can impact our perception (Firestone &amp; Scholl, 2016). Towards this end, per Firestone and Scholl’s argument that many studies fail to distinguish perceptual processes from judgment processes, we added a shorter stimulus presentation time to the experiment to eliminate the potential for judgment processes to occur. Ultimately, we successfully replicated Abado et al.’s findings in both of the time conditions, although some findings had a smaller effect size or less robust statistical significance than Abado et al.’s did. We suggest that U.S. adults indeed exhibit a tendency to pay more attention to phylogenetic threats than to ontogenetic threats. We also tentatively suggest that this attentional bias is not due to judgment processes, and could potentially be a top-down effect. Among other suggestions, we would like future research to study whether these findings are specific to the images that Abado et al.&nbsp;used and continue the top-down effect investigation with EEG technology.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Are certain fears “ready-made” to capture our attention faster than others? Is there a distinction between how people with a fear of snakes perceive snakes and how people with a fear of knives perceive knives? Built upon a history of investigation into the perception of “preparedness” as a category of distinct phobia <span class="citation" data-cites="Hugdahl1989 Seligman1971">(<a href="#ref-Hugdahl1989" role="doc-biblioref">Hugdahl and Johnsen 1989</a>; <a href="#ref-Seligman1971" role="doc-biblioref">Seligman 1971</a>)</span>, a recent visual discrimination experiment from Abado et al.&nbsp;found, in part, that participants identify images of organically-originating threats (spiders) faster than images of man-made threats (guns) <span class="citation" data-cites="Abado2023">(<a href="#ref-Abado2023" role="doc-biblioref">Abado, Aue, and Okon-Singer 2023</a>)</span>. Abado et al.&nbsp;used these findings to suggest that attentional biases, the tendencies of individuals to pay more attention to certain stimuli or aspects of their environment over others, may differ between organically-occurring threats and man-made threats. In this study, we intend to discover both whether this finding is replicable and whether it is based solely in perceptual processes.</p>
<p>The theories preceding Abado et al.&nbsp;have largely suggested that there is indeed a difference between perceptions of types of threats. Seligman (1971) theorized in this direction by dividing the origin of fear into phobias, which are highly selective, resistant to change, and often acquired through single exposure event, and laboratory-induced fears, which are conditioned to any stimuli but fade rapidly. Hugdahl &amp; Johnsen (1989) found evidence in support of Seligman’s hypothesis, suggesting an attentional bias towards evolutionary (phylogenetic) threats. It is not clear, though, whether this difference is a product of the “top-down effect” that our beliefs can impact our perception, or whether it involves more than perceptual processes <span class="citation" data-cites="Firestone2015">(<a href="#ref-Firestone2015" role="doc-biblioref">Firestone and Scholl 2015</a>)</span>. Firestone &amp; Scholl argue that the ostensible top-down effect findings in the literature suffered from pitfalls in the experimental designs, and we think that Abado et al.’s experimental design, in the context of the top-down effect, may have included one such pitfall: because the duration for which participants were shown images was long enough for participants’ perceptual and judgment processes to have occurred before they responded, the observed attention bias could have occurred after perception and therefore would not have been a top-down effect.</p>
<p>Building upon Abado et al., and considering Firestone and Scholl’s reservations, our modified replication will eliminate the potential for the so-called “perception vs.&nbsp;judgment” pitfall by including an additional condition with a reduced image presentation time of 800ms. Therefore, if the interpretation of Abado et al.&nbsp;holds, we hypothesize that at the original 2500ms stimuli presentation time and the new 800ms time, participants will detect spiders faster than birds and not detect guns faster than telephones. Our repeated measures ANOVA would reflect this by showing an interaction between the origin type of stimulus (phylogenetic/ontogenetic) and discrepant object type (threatening/non-threatening) on reaction time. Our pairwise comparisons would reflect this in our data by showing that participants react significantly faster, on average, to phylogenetic threats relative to phylogenetic non-threats, but do not react significantly faster, on average, to ontogenetic threats compared to ontogenetic non-threats. Thus, this modified replication will help us establish the reliability of Abado et al.’s attention bias findings and provide insights into the underlying cognitive processes involved in phylogenetic and ontogenetic threat detection.</p>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<section id="participants" class="level3">
<h3 class="anchored" data-anchor-id="participants">Participants</h3>
<p>The Vassar College Institutional Review Board approved this study. We recruited 75 English-speaking participants aged 18 years or older through the online web-recruitment platform Prolific, the same as used in the original study, paying each of them $2.60 for completing the experiment. All participants were residents of the United States. Though Abado et al.&nbsp;had 144 participants in their final analysis, our sample size was restricted by our budget.&nbsp;</p>
<p>We had pre-registered that we would exclude participants post-experimentally if they reported a history of neurological disorders or ADHD because Prolific does not allow researchers to screen for this information prior to a participant’s completion of the experiment; however, unfortunately, we did not gather this information and thus were unable to make these exclusions.</p>
<p>Directly following data collection but before beginning analysis, we gave the applet a once-over. We found an error in our experiment that caused a significant number (n=31) of participants to not receive both the 2500ms and 800ms time condition manipulations for both the phylogenetic and ontogenetic blocks of stimuli. As performing our pre-registered repeated-measures ANOVA analysis required that all individual participants be exposed to all independent variable manipulations, we excluded these participants from data analysis. We excluded the (n=1) participant who failed to respond with any valid keypress greater than 50% of the time.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Load and process behavioral data, filtering out those whom we cannot perform the RMANOVA on because they didn't get all time manipulations across all stimulus blocks</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>directory <span class="ot">&lt;-</span> <span class="st">"data/Data"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>file_list <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="at">path =</span> directory, <span class="at">recursive =</span> <span class="cn">TRUE</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>csv_files <span class="ot">&lt;-</span> file_list[<span class="fu">grep</span>(<span class="st">"</span><span class="sc">\\</span><span class="st">.csv$"</span>, file_list, <span class="at">ignore.case =</span> <span class="cn">TRUE</span>)]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>dataframes <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (file <span class="cf">in</span> csv_files) {</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  dataframes[[file]] <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(file)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (file <span class="cf">in</span> csv_files) {  </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  temp_df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(file)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    dataframes[[file]] <span class="ot">&lt;-</span> temp_df</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(dataframes)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(dataframes)) {</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  current_df <span class="ot">&lt;-</span> dataframes[[i]]</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">any</span>(<span class="fu">table</span>(current_df<span class="sc">$</span>blocktype, current_df<span class="sc">$</span>time_manipulation) <span class="sc">==</span> <span class="dv">80</span>)) {</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    result <span class="ot">&lt;-</span> <span class="fu">c</span>(result, <span class="fu">names</span>(dataframes)[i])</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>filtered_dataframes <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(dataframes)) {</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  current_df <span class="ot">&lt;-</span> dataframes[[i]]</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">any</span>(<span class="fu">table</span>(current_df<span class="sc">$</span>blocktype, current_df<span class="sc">$</span>time_manipulation) <span class="sc">==</span> <span class="dv">80</span>)) {</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    filtered_dataframes[[<span class="fu">length</span>(filtered_dataframes) <span class="sc">+</span> <span class="dv">1</span>]] <span class="ot">&lt;-</span> current_df</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(filtered_dataframes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We also chose to exclude the (n=1) participant with unreliably inconsistent and problematic behavior, including incorrectly answering about half of the practice trials, over half of the trials in the last block, and a significant number of trials throughout all blocks wrong, despite having demonstrated valid responses on the keyboard multiple times. After these exclusions, (n=41) participants remained (14 male and 27 female).</p>
<p>We also identified two subjects whose response patterns did not match expected behavior, but nonetheless varied reliably in their divergence from expectation. In both cases, these two subjects (<em>lx4ndEBa7j</em> and <em>ly4nYM8zD0</em>) appeared to have mistaken the natures of the stimulus categories. Subject <em>lx4ndEBa7j</em> consistently responded in the phylogenetic blocks as though spiders were non-threatening, and <em>ly4nYM8zD0</em> consistently responded in the ontogenetic response as though the telephones were threatening objects. We opted to include these subjects in the data analysis, as not only did they respond to the prompts in the practice round with a high degree of accuracy, but it is difficult to know, without having distributed a follow-up questionnaire, why precisely these subjects answered in the fashion they did. While it is possible that they misunderstood the tasks, it is also possible that they simply held non-normative views about the degree of threat posed by either spiders or phones, in which case their data, as nonetheless part of the target population, should be included.</p>
</section>
<section id="procedure" class="level3">
<h3 class="anchored" data-anchor-id="procedure">Procedure</h3>
<p>Pre-registration materials for this study are available on the Open Science Framework at <a href="https://osf.io/x5v6g" class="uri">https://osf.io/x5v6g</a>. All data are available on the Open Science Framework at <a href="https://osf.io/k93an/" class="uri">https://osf.io/k93an/</a>. We used custom software deployed in a web browser with the <em>jsPsych</em> framework, which participants viewed via their own laptop or desktop <span class="citation" data-cites="Leeuw2023">(<a href="#ref-Leeuw2023" role="doc-biblioref">Leeuw, Gilbert, and Luchterhandt 2023</a>)</span>.</p>
<p>Participants experienced a modified version of the experiment in Abado et al.&nbsp;(Figure 1A), which used the well-known “discrepant-object” paradigm for task construction, whereby an array of objects is juxtaposed, and subjects are made to determine which one of the objects is different from the rest. In each trial, participants initially saw a fixation cross (+) on their screen for 500ms. Next, participants saw a 3x3 grid of images. In half of the trials, the nine images were of organically-occurring items (phylogenetic). In the other half of the trials, the nine images were of a man-made origin (ontogenetic).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-one" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-one-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figure1.jpeg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-one-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: (A) ​​Schematic of the visual discrimination task. (B) Example ontogenetic no discrepant stimulus. (C) Example phylogenetic non-threatening discrepant stimulus. (D) Example ontogenetic threatening discrepant stimulus
</figcaption>
</figure>
</div>
</div>
</div>
<p>Within each 3x3 grid, participants saw at least eight distractor images: butterflies in the phylogenetic trials and staplers in the ontogenetic trials. Like Abado et al., we used this number of distractors to give the task some reasonable level of difficulty without being overly taxing. In ten percent of the trials, the ninth image was of another butterfly or spider, meaning participants viewed nine distractor images (Figure 1B). In forty-five percent of the trials, the ninth image was of a bird or old telephone, meaning participants viewed eight distractor images and one non-threatening discrepant image (Figure 1C). In the remaining forty-five percent of the trials, the ninth image was of a spider or gun, meaning participants viewed eight distractor images and one threatening discrepant image (Figure 1D). We were interested in analyzing the ninety percent of trials that contained a discrepant image, but we included the trials without a discrepant image both for true replication and to serve as attention checks.&nbsp;</p>
<p>Participants saw the 3x3 image grid for 2500ms in half of the phylogenetic trials and half of the ontogenetic trials, and 800ms in the other halves. We used 2500ms to replicate Abado et al.&nbsp;and 800ms to address the perception vs.&nbsp;judgment pitfall. We specifically chose 800ms because this was the shortest time frame that still preserved reasonable average accuracy rates of around eighty percent when we piloted our experiment on our peers; thus, we assumed that this time period mitigated the potential for judgment while still allowing participants to perceive stimuli.</p>
<p>After viewing the stimulus, participants saw a randomly generated 3x3 grid of masks for 150ms, whose contents were a flattened gaussian noise distribution. Their screen then remained blank for either 5000ms or until they responded, although participants were able to respond at any time upon a stimulus first appearing on their screen. Participants responded by either pressing the ‘P’ key on their keyboard to indicate that the stimulus contained one different and non-threatening image, the ‘Q’ key to indicate that the stimulus contained one different and threatening image, or the ‘SPACE’ bar to indicate that the stimulus did not contain a different image.</p>
<p>We used the <em>jsPsych</em> randomization feature to ensure that presentation time, origin type (phylogenetic/ontogenetic), and discrepant type were randomly assigned in every trial. Each image in each 3x3 grid was randomly selected from the bank of images specific to the intended image type (e.g., a grid containing nine phylogenetic distractors randomly selected nine images from the bank of butterfly images). No two trials were visually identical unless by random occurrence.</p>
<p>Participants completed four blocks of 90 trials in addition to 20 practice trials for true replication. We created the four blocks for participant experience; none of the four blocks performed a different procedure or were limited to a certain condition.</p>
<p>While Abado et al.&nbsp;used images with white backgrounds and images with complex backgrounds, we only used images with white backgrounds because we were not interested in overly complicating the design with additional variables that were not closely relevant to our research question. We sourced the same 665 white-background images that Abado et al.&nbsp;used and uploaded to their OSF page (<a href="https://osf.io/64nzq/" class="uri">https://osf.io/64nzq/</a>), but sourced different practice trial images. In the practice trials, we used spoons as ontogenetic distractors, rulers as ontogenetic non-threatening discrepants, knives as ontogenetic threatening discrepants, kittens as phylogenetic distractors, bunnies as phylogenetic non-threatening discrepants, and tigers as phylogenetic threatening discrepants. Also, rather than either 800ms or 2500ms, the presentation times of practice trial stimuli decreased in intervals of 100ms from 3000ms to 1100ms so participants could ease into shorter time intervals prior to beginning the real trials.</p>
</section>
<section id="data-pre-processing" class="level3">
<h3 class="anchored" data-anchor-id="data-pre-processing">Data Pre-Processing</h3>
<p>We plotted a simple histogram of reaction time (ms), faceted by group and colored according to time conditions, to observe the response distributions and get a better sense of what responses might be considered outliers (Figure 2). Per our pre-registered qualitative approach to exclusion criteria, we looked for any participants whose reaction times, on average, were shorter than the bulk of responses (&lt;300ms) or longer than the bulk of responses (&gt;3000ms). No participant fit this criteria; however, as the individual reaction times outside of these thresholds were likely results of errors or unrepresentative of the population, we removed all individual reaction times that were less than 300ms or greater than 3000ms.</p>
<div class="cell" data-description="Plots the sample in terms of response time as a histogram (geom area for filled polygons) to each condition, to set cutoff points.">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">## "Preprocessing II: Sample Cutoff Analysis"</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>rt <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(data<span class="sc">$</span>rt)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>data_clean <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(time_manipulation <span class="sc">!=</span> <span class="fu">is.na</span>(<span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(roundtype <span class="sc">==</span> <span class="st">"experimental"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>task <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Ontogenetic_Distractor_notarget"</span>, <span class="st">"Phylogenetic_Distractor_notarget"</span>)) </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>data_clean_task <span class="ot">&lt;-</span> data_clean <span class="sc">%&gt;%</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">task =</span> <span class="fu">str_replace</span>(task, <span class="st">"(</span><span class="sc">\\</span><span class="st">w+)_(</span><span class="sc">\\</span><span class="st">w+)_(</span><span class="sc">\\</span><span class="st">w+)_(</span><span class="sc">\\</span><span class="st">w+)"</span>, <span class="st">"</span><span class="sc">\\</span><span class="st">1 </span><span class="sc">\\</span><span class="st">2 (</span><span class="sc">\\</span><span class="st">3 </span><span class="sc">\\</span><span class="st">4)"</span>))</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>none <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data_clean_task, <span class="fu">aes</span>(<span class="at">x =</span> rt, <span class="at">y =</span> <span class="fu">stat</span>(count), <span class="at">fill =</span> <span class="fu">factor</span>(time_manipulation))) <span class="sc">+</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">stat =</span> <span class="st">"bin"</span>, <span class="at">binwidth =</span> <span class="dv">10</span>, <span class="at">position =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">name =</span> <span class="st">"Response Time (rt)"</span>) <span class="sc">+</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_sqrt</span>() <span class="sc">+</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_paletteer_d</span>(<span class="st">"MetBrewer::Signac"</span>) <span class="sc">+</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_dark</span>(<span class="at">base_size =</span> <span class="dv">8</span>, <span class="at">base_family =</span> <span class="st">"Ubuntu"</span>) <span class="sc">+</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Count"</span>, <span class="at">fill =</span> <span class="st">"Time Manipulation"</span>) <span class="sc">+</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>task) <span class="sc">+</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">7</span>),</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">colour =</span> <span class="cn">NA</span>),</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"grey21"</span>, <span class="at">colour =</span> <span class="cn">NA</span>),</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">colour =</span> <span class="cn">NA</span>)) <span class="sc">+</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(<span class="dv">300</span>, <span class="dv">3000</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fl">0.6</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">1150</span>, <span class="at">y =</span> <span class="cn">Inf</span>, <span class="at">label =</span> <span class="st">"min. exclusion threshold (300ms)"</span>, </span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>           <span class="at">vjust =</span> <span class="fl">1.8</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fl">1.2</span>, <span class="at">angle =</span> <span class="dv">360</span>, <span class="at">fontface =</span> <span class="st">"italic"</span>) <span class="sc">+</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">3900</span>, <span class="at">y =</span> <span class="cn">Inf</span>, <span class="at">label =</span> <span class="st">"max. exclusion threshold (3000ms)"</span>, </span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>           <span class="at">vjust =</span> <span class="fl">1.8</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fl">1.2</span>, <span class="at">angle =</span> <span class="dv">360</span>, <span class="at">fontface =</span> <span class="st">"italic"</span>)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(none)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-preprocessing" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-preprocessing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="SG-Analysis_darkmode_files/figure-html/fig-preprocessing-1.svg" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-preprocessing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Histograms of reaction times for each trial type of interest. Dotted vertical lines represent the exclusion thresholds.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-description="Filters all trials based off of the above cutoffs and removes the two subjects enumerated above">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>filtered.data <span class="ot">&lt;-</span> data_clean <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">as.numeric</span>(rt) <span class="sc">&gt;</span> <span class="dv">300</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">as.numeric</span>(rt) <span class="sc">&lt;</span> <span class="dv">3000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>unique_identifier <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"sIZWIAwLIO"</span>, <span class="st">"bYlzHPOxUs"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>We conducted our analyses in the <em>R</em> environment, using the <em>splithalf</em> package for split-half analysis <span class="citation" data-cites="Parsons2021">(<a href="#ref-Parsons2021" role="doc-biblioref">Parsons 2021</a>)</span> as well as several packages from the <em>tidyverse</em> <span class="citation" data-cites="Wickham2019 RCT2024">(<a href="#ref-Wickham2019" role="doc-biblioref">Wickham et al. 2019</a>; <a href="#ref-RCT2024" role="doc-biblioref">R Core Team 2024</a>)</span>.</p>
<p>We performed our pre-registered split-half reliability, repeated measures <em>ANOVA</em>, and a Bayesian Mixed Modeling analysis for this experiment. We also performed post-hoc pairwise comparisons to expand upon our <em>ANOVA</em> findings and exploratory accuracy analysis to assess data quality. The split-half reliability analysis allowed us to assess the reliability of our data. <em>ANOVA</em> and pairwise comparisons allowed us to uncover main effects related to our hypotheses. The Bayesian Mixed Modeling, while not essential to our investigation, gave us insight into whether group-level differences in reaction time could be explained better by discrepant type than by presentation time.</p>
<section id="split-half-reliability-analysis" class="level3">
<h3 class="anchored" data-anchor-id="split-half-reliability-analysis">Split-Half Reliability Analysis</h3>
<p>In order to truly replicate Abado et al., we conducted split-wise analyses of attention bias. This allowed us to assess the degree to which, in each set of trials corresponding to a given pairing of independent variables, a given subject varied consistently in their attention bias (the difference between threatening and non-threatening trials). This gave us a solid proxy for the reliability of our sample. Shown in Figure 3, the distributions of reliabilities were roughly normal and centered with a mean around 0.77 for all configurations, which we found especially impressive given the aforementioned subjects who responded in unexpected ways. This suggests that participants were relatively consistent in their responses.</p>
<div class="cell" data-description="The code for the replicated splithalf analyses (following filtration procedures and attention bias computation from original)">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>correct_trials <span class="ot">&lt;-</span> filtered.data <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(correct <span class="sc">==</span> <span class="st">"true"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>attention_bias <span class="ot">&lt;-</span> correct_trials <span class="sc">%&gt;%</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">distractortype =</span> <span class="fu">sub</span>(<span class="st">"^.*?_.*?_(.*)$"</span>, <span class="st">"</span><span class="sc">\\</span><span class="st">1"</span>, task),</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">threat_vs_neutral_rt =</span> <span class="fu">if_else</span>(distractortype <span class="sc">==</span> <span class="st">"Threat_target"</span>, rt, <span class="sc">-</span>rt)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>task_consistency_time <span class="ot">&lt;-</span> <span class="fu">splithalf</span>(<span class="at">data =</span> attention_bias,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>                        <span class="at">outcome =</span> <span class="st">"RT"</span>,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>                        <span class="at">score =</span> <span class="st">"average"</span>,</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>                        <span class="at">conditionlist =</span> <span class="fu">c</span>(<span class="st">"800"</span>, <span class="st">"2500"</span>),</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>                        <span class="at">halftype =</span> <span class="st">"random"</span>,</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>                        <span class="at">permutations =</span> <span class="dv">5000</span>,</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>                        <span class="at">var.RT =</span> <span class="st">"threat_vs_neutral_rt"</span>,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>                        <span class="at">var.condition =</span> <span class="st">"time_manipulation"</span>,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>                        <span class="at">var.participant =</span> <span class="st">"unique_identifier"</span>,</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>                        <span class="at">average =</span> <span class="st">"mean"</span>,</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>                        <span class="at">check =</span> <span class="cn">TRUE</span>, <span class="at">plot =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>task_consistency_block <span class="ot">&lt;-</span> <span class="fu">splithalf</span>(<span class="at">data =</span> attention_bias,</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>                        <span class="at">outcome =</span> <span class="st">"RT"</span>,</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>                        <span class="at">score =</span> <span class="st">"average"</span>,</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>                        <span class="at">conditionlist =</span> <span class="fu">c</span>(<span class="st">"Ontogenetic"</span>, <span class="st">"Phylogenetic"</span>),</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>                        <span class="at">halftype =</span> <span class="st">"random"</span>,</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>                        <span class="at">permutations =</span> <span class="dv">5000</span>,</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>                        <span class="at">var.RT =</span> <span class="st">"threat_vs_neutral_rt"</span>,</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>                        <span class="at">var.condition =</span> <span class="st">"blocktype"</span>,</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>                        <span class="at">var.participant =</span> <span class="st">"unique_identifier"</span>,</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>                        <span class="at">average =</span> <span class="st">"mean"</span>,</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>                        <span class="at">check =</span> <span class="cn">TRUE</span>, <span class="at">plot =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>plotsplithalferI <span class="ot">&lt;-</span> task_consistency_time[[<span class="st">"plot"</span>]]</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>plotsplithalferII <span class="ot">&lt;-</span> task_consistency_block[[<span class="st">"plot"</span>]]</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>plotsplithalferI <span class="ot">&lt;-</span> plotsplithalferI <span class="sc">+</span> <span class="fu">theme_fivethirtyeight</span>(<span class="at">base_size =</span> <span class="fl">8.5</span>, <span class="at">base_family =</span> <span class="st">"Ubuntu"</span>) <span class="sc">+</span></span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">9</span>),</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">12</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="dv">10</span>, <span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">0</span>)),</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>)) <span class="sc">+</span></span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>        <span class="fu">scale_color_paletteer_d</span>(<span class="st">`</span><span class="at">"vapoRwave::jazzCup"</span><span class="st">`</span>) <span class="sc">+</span></span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>        <span class="fu">labs</span>(<span class="at">color=</span><span class="st">'Time Manipulation'</span>, <span class="at">fill=</span><span class="st">'Time Manipulation'</span>, margin) <span class="sc">+</span></span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>        <span class="fu">scale_fill_paletteer_d</span>(<span class="st">`</span><span class="at">"vapoRwave::jazzCup"</span><span class="st">`</span>) <span class="sc">+</span></span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ylab</span>(<span class="st">"Intersubject Reliability"</span>) <span class="sc">+</span></span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a>        <span class="fu">xlab</span>(<span class="st">"Time Manipulation"</span>)</span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a>plotsplithalferII <span class="ot">&lt;-</span> plotsplithalferII <span class="sc">+</span> <span class="fu">theme_fivethirtyeight</span>(<span class="at">base_size =</span> <span class="fl">8.5</span>, <span class="at">base_family =</span> <span class="st">"Ubuntu"</span>) <span class="sc">+</span></span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">9</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="dv">10</span>, <span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">0</span>)),</span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>)) <span class="sc">+</span></span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a>        <span class="fu">scale_color_paletteer_d</span>(<span class="st">`</span><span class="at">"ghibli::SpiritedLight"</span><span class="st">`</span>) <span class="sc">+</span></span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a>        <span class="fu">labs</span>(<span class="at">color=</span><span class="st">'Stimulus Origin'</span>, <span class="at">fill=</span><span class="st">'Stimulus Origin'</span>) <span class="sc">+</span></span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a>        <span class="fu">scale_fill_paletteer_d</span>(<span class="st">`</span><span class="at">"lisa::EdvardMunch"</span><span class="st">`</span>) <span class="sc">+</span></span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ylab</span>(<span class="st">"Intersubject Reliability"</span>) <span class="sc">+</span></span>
<span id="cb4-59"><a href="#cb4-59" aria-hidden="true" tabindex="-1"></a>        <span class="fu">xlab</span>(<span class="st">"Stimulus Character"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(plotsplithalferI, plotsplithalferII, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">widths =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>), <span class="at">padding =</span> <span class="fu">unit</span>(<span class="dv">20</span>, <span class="st">"px"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-splithalf" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-splithalf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="SG-Analysis_darkmode_files/figure-html/fig-splithalf-1.svg" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-splithalf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Split-half reliabiliy plots split by time manipulation (left) and stimulus character (right).
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="exploratory-accuracy-analysis" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-accuracy-analysis">Exploratory Accuracy Analysis</h3>
<p>Though we did not pre-register exploratory accuracy analyses, in the interest of ensuring that our task was sufficiently robust, we ran a separate <em>ANOVA</em> and pairwise comparisons on accuracy to assess whether meaningful discrepancies in difficulty between conditions existed in the data. While the results for the <em>ANOVA</em> showed highly significant effects of both origin type on accuracy and presentation time on accuracy, pairwise comparisons revealed that these effects were largely irrelevant to our analyses of reaction times (Figure 4). Pairwise methods made better sense of the latent sources of variance in the data, revealing that while approximately 1/4 of the post-hoc pairwise comparisons were significant, these difference estimates, in absolute terms, were unlikely to have much of a practical impact on the data quality surrounding our variable of interest. Indeed, the single largest estimated discrepancy between categories was an average drop of 3 questions. These results were reasonable, considering both the largest estimated discrepancy and our inclusion of the two aforementioned outlier subjects. If we, like Abado et al., were able to draw from more observations, it is very likely that these differences would not have been present.</p>
<div class="cell" title="Preprocessing V: Formatting/Typings">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">## This is the code we used to double-check the typing and further drill our dataset down to the parameters of interest.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Prepares dataset for ANOVA by ensuring all the variables are present and typed correctly for function calls to lmer, emmeans, and aov.</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>filtered.data_plusanovagroups <span class="ot">&lt;-</span> filtered.data <span class="sc">%&gt;%</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">distractortype =</span> <span class="fu">sub</span>(<span class="st">"^.*?_.*?_(.*)$"</span>, <span class="st">"</span><span class="sc">\\</span><span class="st">1"</span>, task),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">correct =</span> <span class="fu">as.logical</span>(correct)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subject_id, unique_identifier, blocktype, distractortype, time_manipulation, task) <span class="sc">%&gt;%</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">individual_subject_mean_rt =</span> <span class="fu">mean</span>(<span class="fu">as.numeric</span>(rt), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">individual_subject_sd_rt =</span> <span class="fu">sd</span>(<span class="fu">as.numeric</span>(rt), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">number_correct =</span> <span class="fu">sum</span>(correct, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_responses =</span> <span class="fu">n</span>(),</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">subject_accuracy =</span> number_correct <span class="sc">/</span> total_responses,</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">subject_timeelapsed =</span> <span class="fu">max</span>(time_elapsed, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">-</span> <span class="fu">min</span>(time_elapsed, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> <span class="fu">ungroup</span>(subject_id, unique_identifier)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="co"># set appropriate types for vars (if they represent factor related stuff)</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>filtered.data_plusanovagroups<span class="sc">$</span>blocktype <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(filtered.data_plusanovagroups<span class="sc">$</span>blocktype)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>filtered.data_plusanovagroups<span class="sc">$</span>distractortype <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(filtered.data_plusanovagroups<span class="sc">$</span>distractortype)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>filtered.data_plusanovagroups<span class="sc">$</span>time_manipulation <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(filtered.data_plusanovagroups<span class="sc">$</span>time_manipulation)</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>filtered.data_plusanovagroups<span class="sc">$</span>subject_id <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(filtered.data_plusanovagroups<span class="sc">$</span>subject_id)</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>filtered.data_plusanovagroups<span class="sc">$</span>individual_subject_mean_rt <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(filtered.data_plusanovagroups<span class="sc">$</span>individual_subject_mean_rt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>model_accuracyanova <span class="ot">&lt;-</span> <span class="fu">aov</span>(number_correct <span class="sc">~</span> blocktype <span class="sc">*</span> distractortype <span class="sc">*</span> time_manipulation <span class="sc">+</span> <span class="fu">Error</span>(unique_identifier), <span class="at">data =</span> filtered.data_plusanovagroups)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>new_check <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_accuracyanova)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>emm_res_accuracy <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(model_accuracyanova, <span class="sc">~</span> blocktype <span class="sc">*</span> distractortype <span class="sc">*</span> time_manipulation)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>posthoc_pairwisecomp_accuracy <span class="ot">&lt;-</span> <span class="fu">pairs</span>(emm_res_accuracy, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>df_posthoc_pairwisecomps_accuracy <span class="ot">&lt;-</span> <span class="fu">summary</span>(posthoc_pairwisecomp_accuracy)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>df_posthoc_pairwisecomps_accuracy<span class="sc">$</span>p.value <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(df_posthoc_pairwisecomps_accuracy<span class="sc">$</span>p.value)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>df_posthoc_pairwisecomps_accuracy<span class="sc">$</span>contrast <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"_target time_manipulation(</span><span class="sc">\\</span><span class="st">d+)"</span>, <span class="st">" @ </span><span class="sc">\\</span><span class="st">1ms"</span>, df_posthoc_pairwisecomps_accuracy<span class="sc">$</span>contrast)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>df_posthoc_pairwisecomps_accuracy <span class="ot">&lt;-</span> df_posthoc_pairwisecomps_accuracy <span class="sc">%&gt;%</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">within_timewindow =</span> {</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>      time_left <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(<span class="fu">str_split_fixed</span>(contrast, <span class="st">" - "</span>, <span class="dv">2</span>)[, <span class="dv">1</span>], <span class="st">"</span><span class="sc">\\</span><span class="st">d+ms"</span>)</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>      time_right <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(<span class="fu">str_split_fixed</span>(contrast, <span class="st">" - "</span>, <span class="dv">2</span>)[, <span class="dv">2</span>], <span class="st">"</span><span class="sc">\\</span><span class="st">d+ms"</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>      time_left <span class="sc">==</span> time_right</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">within_stimuluscat =</span> {</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>      cat_left <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(<span class="fu">str_split_fixed</span>(contrast, <span class="st">" - "</span>, <span class="dv">2</span>)[, <span class="dv">1</span>], <span class="st">"^</span><span class="sc">\\</span><span class="st">w+"</span>)</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>      cat_right <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(<span class="fu">str_split_fixed</span>(contrast, <span class="st">" - "</span>, <span class="dv">2</span>)[, <span class="dv">2</span>], <span class="st">"^</span><span class="sc">\\</span><span class="st">w+"</span>)</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>      <span class="fu">paste</span>(cat_left, <span class="fu">ifelse</span>(cat_left <span class="sc">==</span> cat_right, <span class="st">"TRUE"</span>, <span class="st">"FALSE"</span>))</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>filtered.data_plusanovagroups_pretty <span class="ot">&lt;-</span> filtered.data_plusanovagroups <span class="sc">%&gt;%</span></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">task =</span> <span class="fu">gsub</span>(<span class="st">"Ontogenetic_Distractor_(.*?)_target"</span>, <span class="st">"Ontogenetic </span><span class="sc">\\</span><span class="st">1"</span>, task),</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>         <span class="at">task =</span> <span class="fu">gsub</span>(<span class="st">"Phylogenetic_Distractor_(.*?)_target"</span>, <span class="st">"Phylogenetic </span><span class="sc">\\</span><span class="st">1"</span>, task))</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>meandamage <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(filtered.data_plusanovagroups_pretty, <span class="fu">aes</span>(<span class="at">x =</span> task, <span class="at">y =</span> subject_accuracy, <span class="at">fill =</span> task)) <span class="sc">+</span></span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_paletteer_d</span>(<span class="at">palette =</span> <span class="st">"ghibli::PonyoMedium"</span>) <span class="sc">+</span> </span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>time_manipulation) <span class="sc">+</span></span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Simplified Accuracy Plot by Task"</span>,</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Task Type"</span>,</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Subject Accuracy"</span>,</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Task Type"</span>) <span class="sc">+</span></span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_fivethirtyeight</span>(<span class="at">base_size =</span> <span class="fl">9.5</span>, <span class="at">base_family =</span> <span class="st">"Ubuntu"</span>) <span class="sc">+</span></span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="dv">10</span>, <span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">0</span>)),</span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">4</span>),</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">12</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="dv">0</span>, <span class="dv">20</span>, <span class="dv">20</span>, <span class="dv">0</span>)),</span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>))</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>df_for_publication_2 <span class="ot">&lt;-</span> df_posthoc_pairwisecomps_accuracy <span class="sc">%&gt;%</span></span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(meandamage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-saccuracy" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-saccuracy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="SG-Analysis_darkmode_files/figure-html/fig-saccuracy-1.svg" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-saccuracy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Mean accuracy by type of trial
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df_for_publication_2 <span class="ot">&lt;-</span> <span class="fu">setNames</span>(df_for_publication_2, <span class="fu">c</span>(<span class="st">"Comparison"</span>,<span class="st">"Estimate"</span>,<span class="st">"SE"</span>, <span class="st">"df"</span>, <span class="st">"T-ratio"</span>, <span class="st">"P-Value"</span>, <span class="st">"Is within time window?"</span>, <span class="st">"Is within stimulus category"</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(df_for_publication_2, <span class="st">"html"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Comparison</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">T-ratio</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">P-Value</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Is within time window?</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Is within stimulus category</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Phylogenetic Nonthreat @ 800ms - Ontogenetic Threat @ 800ms</td>
<td style="text-align: right;">-2.487805</td>
<td style="text-align: right;">0.5665597</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">-4.391073</td>
<td style="text-align: right;">0.0004218</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">Phylogenetic FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">Phylogenetic Nonthreat @ 800ms - Phylogenetic Threat @ 800ms</td>
<td style="text-align: right;">-1.878049</td>
<td style="text-align: right;">0.5665597</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">-3.314830</td>
<td style="text-align: right;">0.0228358</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">Phylogenetic TRUE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Phylogenetic Nonthreat @ 800ms - Ontogenetic Nonthreat @ 2500ms</td>
<td style="text-align: right;">-2.487805</td>
<td style="text-align: right;">0.5665597</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">-4.391073</td>
<td style="text-align: right;">0.0004218</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">Phylogenetic FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">Phylogenetic Nonthreat @ 800ms - Ontogenetic Threat @ 2500ms</td>
<td style="text-align: right;">-3.317073</td>
<td style="text-align: right;">0.5665597</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">-5.854764</td>
<td style="text-align: right;">0.0000004</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">Phylogenetic FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Phylogenetic Nonthreat @ 800ms - Phylogenetic Threat @ 2500ms</td>
<td style="text-align: right;">-2.487805</td>
<td style="text-align: right;">0.5665597</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">-4.391073</td>
<td style="text-align: right;">0.0004218</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">Phylogenetic TRUE</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ontogenetic Threat @ 800ms - Phylogenetic Nonthreat @ 2500ms</td>
<td style="text-align: right;">1.975610</td>
<td style="text-align: right;">0.5665597</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">3.487029</td>
<td style="text-align: right;">0.0130487</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">Ontogenetic FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ontogenetic Nonthreat @ 2500ms - Phylogenetic Nonthreat @ 2500ms</td>
<td style="text-align: right;">1.975610</td>
<td style="text-align: right;">0.5665597</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">3.487029</td>
<td style="text-align: right;">0.0130487</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">Ontogenetic FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">Phylogenetic Nonthreat @ 2500ms - Ontogenetic Threat @ 2500ms</td>
<td style="text-align: right;">-2.804878</td>
<td style="text-align: right;">0.5665597</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">-4.950720</td>
<td style="text-align: right;">0.0000348</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">Phylogenetic FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Phylogenetic Nonthreat @ 2500ms - Phylogenetic Threat @ 2500ms</td>
<td style="text-align: right;">-1.975610</td>
<td style="text-align: right;">0.5665597</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">-3.487029</td>
<td style="text-align: right;">0.0130487</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">Phylogenetic TRUE</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</section>
<section id="reaction-time-descriptives" class="level3">
<h3 class="anchored" data-anchor-id="reaction-time-descriptives">Reaction Time Descriptives</h3>
<p>Focusing our attention to areas of interest, we then averaged reaction times by subject (across trials) along each of the three independent variables of interest: stimulus origin (ontogenetic/phylogenetic), discrepant type (threatening/non-threatening), and time manipulation (2500ms/800ms). We used these to visually gain a sense of general patterns in the data, as visible in Figure 5.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Graphs and Plots / Remappings for ggplot - main graph of means and the like to visualize what patterns of interest are encapsulated by the anova.</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>janmeans_main <span class="ot">&lt;-</span> filtered.data_plusanovagroups <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(distractortype <span class="sc">==</span> <span class="st">"Threat_target"</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>janmeans_aes1 <span class="ot">&lt;-</span> filtered.data_plusanovagroups <span class="sc">%&gt;%</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(distractortype <span class="sc">==</span> <span class="st">"Threat_target"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(blocktype, time_manipulation) <span class="sc">%&gt;%</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(<span class="at">point_mean =</span> <span class="fu">mean</span>(individual_subject_mean_rt), <span class="at">point_sd =</span> <span class="fu">mean</span>(individual_subject_sd_rt)) <span class="sc">%&gt;%</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(time_manipulation <span class="sc">==</span> <span class="st">"2500"</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>janmeans_aes2 <span class="ot">&lt;-</span> filtered.data_plusanovagroups <span class="sc">%&gt;%</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(distractortype <span class="sc">==</span> <span class="st">"Threat_target"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(blocktype, time_manipulation) <span class="sc">%&gt;%</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(<span class="at">point_mean =</span> <span class="fu">mean</span>(individual_subject_mean_rt), <span class="at">point_sd =</span> <span class="fu">mean</span>(individual_subject_sd_rt)) <span class="sc">%&gt;%</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(time_manipulation <span class="sc">==</span> <span class="st">"800"</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>aes_data <span class="ot">&lt;-</span> janmeans_main <span class="sc">%&gt;%</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(blocktype, time_manipulation) <span class="sc">%&gt;%</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">lower =</span> <span class="fu">mean</span>(individual_subject_mean_rt) <span class="sc">-</span> <span class="fu">sd</span>(individual_subject_mean_rt),</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">middle =</span> <span class="fu">mean</span>(individual_subject_mean_rt),</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">upper =</span> <span class="fu">mean</span>(individual_subject_mean_rt) <span class="sc">+</span> <span class="fu">sd</span>(individual_subject_mean_rt),</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">ymin =</span> <span class="fu">min</span>(individual_subject_mean_rt),</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">ymax =</span> <span class="fu">max</span>(individual_subject_mean_rt),</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>base_size <span class="ot">&lt;-</span> <span class="fl">1.21</span></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>top_size <span class="ot">&lt;-</span> <span class="fl">1.20</span></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>new_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(aes_data, <span class="fu">aes</span>(<span class="at">x =</span> blocktype, <span class="at">y =</span> middle, <span class="at">color =</span> time_manipulation, <span class="at">fill =</span> time_manipulation)) <span class="sc">+</span></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">lower =</span> lower, <span class="at">upper =</span> upper, <span class="at">ymin =</span> ymin, <span class="at">ymax =</span> ymax, <span class="at">middle =</span> middle, <span class="at">alpha =</span> <span class="fl">0.1</span>),</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>               <span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.31</span>), <span class="at">width =</span> <span class="fl">0.3</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Stimulus Origin"</span>) <span class="sc">+</span></span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> janmeans_aes1, <span class="fu">aes</span>(<span class="at">x =</span> blocktype, <span class="at">y =</span> point_mean, <span class="at">group =</span> time_manipulation), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> base_size, <span class="at">alpha =</span> <span class="fl">0.9</span>, <span class="at">color =</span> <span class="st">"#401419"</span>) <span class="sc">+</span></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> janmeans_aes2, <span class="fu">aes</span>(<span class="at">x =</span> blocktype, <span class="at">y =</span> point_mean, <span class="at">group =</span> time_manipulation), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> base_size, <span class="at">alpha =</span> <span class="fl">0.8</span>, <span class="at">color =</span> <span class="st">"#401419"</span>) <span class="sc">+</span></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> janmeans_aes1, <span class="fu">aes</span>(<span class="at">x =</span> blocktype, <span class="at">y =</span> point_mean, <span class="at">group =</span> time_manipulation), <span class="at">linetype =</span> <span class="st">"solid"</span>, <span class="at">size =</span> top_size, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> janmeans_aes2, <span class="fu">aes</span>(<span class="at">x =</span> blocktype, <span class="at">y =</span> point_mean, <span class="at">group =</span> time_manipulation), <span class="at">linetype =</span> <span class="st">"solid"</span>, <span class="at">size =</span> top_size, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">color=</span><span class="st">'Time Manipulation'</span>, <span class="at">fill=</span><span class="st">'Time Manipulation'</span>) <span class="sc">+</span></span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_paletteer_d</span>(<span class="st">"wesanderson::Moonrise3"</span>) <span class="sc">+</span></span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_paletteer_d</span>(<span class="st">`</span><span class="at">"wesanderson::Moonrise3"</span><span class="st">`</span>) <span class="sc">+</span></span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_fivethirtyeight</span>(<span class="at">base_size =</span> <span class="fl">9.5</span>, <span class="at">base_family =</span> <span class="st">"Ubuntu"</span>) <span class="sc">+</span></span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">12</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="dv">20</span>, <span class="dv">20</span>, <span class="st">"pt"</span>)),</span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>)) <span class="sc">+</span></span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Reaction Time (ms)"</span>) <span class="sc">+</span></span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">caption =</span> <span class="st">"Note: Box and Whisker plot modified from default ggplot2 to put means in place of medians, and Standard Deviation in lieu of 1st/3rd IQR"</span>)</span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(new_graph)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-janmeanslol" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-janmeanslol-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="SG-Analysis_darkmode_files/figure-html/fig-janmeanslol-1.svg" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-janmeanslol-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Average reaction time as a function of time manipulation and stimulus origin. These box and whisker plots show mean instead of median, as well as standard deviation in lieu of first and third IQRs”
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="rmanova-and-pairwise-comparison-analyses" class="level3">
<h3 class="anchored" data-anchor-id="rmanova-and-pairwise-comparison-analyses">RMANOVA and Pairwise Comparison Analyses</h3>
<p>We then conducted a repeated-measures 3x2 <em>ANOVA</em> on reaction time (with dF=40 residuals for within-subjects random factors, and dF=6 between-subjects interactions between our IVs). We pre-registered a 2x2 <em>RMANOVA</em> because we originally intended to combine origin type and discrepant type into one independent variable. However, after data collection, we realized that initializing a comparison involving time manipulation, origin type, and discrepant type separately would provide more granular insight as to the extent of effects on reaction time contributed by each variable.</p>
<p>In our <em>RMANOVA</em>, we failed to find a significant effect of stimulus origin type on the patterns of reaction time exhibited by participants across all trials (<em>F</em>=0.077, <em>p</em>=0.7819; compare to Abado et al.’s <em>F</em>=10.88, <em>p</em>=0.001). Inconsistent with Abado et al., this suggests that participants did not respond at a different speed solely depending on whether a stimulus was made up of organically-occurring images or man-made images. We found a highly significant impact of our time manipulation on the speed of subjects’ responses (<em>F</em>=194.616, <em>p</em>&lt;0.0001), suggesting that participants responded faster when a stimulus was shown for 800ms compared to 2500ms. Also, we unsurprisingly found a highly significant impact on variance within reaction time of threatening relative to non-threatening discrepants in stimuli (<em>F</em>=34.508, <em>p</em> &lt; .0001; compare to Abado et al.’s <em>F</em>=18.07, <em>p</em> &lt; 0.001). This effect, consistent with and even greater than Abado et al.’s observed effect, suggests that participants responded faster when the discrepant image in a stimulus was a threat compared to when it was a non-threat. While important to note, especially in regards to replicating Abado et al., none of these findings directly concern the research question at hand.</p>
<p>Most relevant in our <em>RMANOVA</em> to our hypotheses, we found a significant interaction effect between origin type and discrepant type on reaction time (<em>F</em>=6.285, <em>p</em>=0.0127; compare to Abado et al.’s <em>F</em>=173.75, <em>p</em> &lt; 0.001), though the effect was not as large nor as significant as Abado et al.’s observed effect. Tentatively consistent with Abado et al., this suggests that origin type and discrepant type, in combination, affect reaction times in a way that cannot be explained by the individual effects of each factor alone. We used post-hoc pairwise comparisons to uncover more information related to this finding.</p>
<div class="cell" data-description="A three by two repeated measures analysis of variance (RMANOVA) used with the discrepant (threatening, neutral) and the stimulus type (phylogenetic, ontogenetic), both within-subjects. If the presentation time manipulation itself has an effect on reaction time–which indicates that judgment may be at play instead of perception—then the ANOVA should show that a greater proportion of the variance is explained in terms of between-subject factors than within-subject factors. This column returns">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>model_rmanova <span class="ot">&lt;-</span> <span class="fu">aov</span>(individual_subject_mean_rt <span class="sc">~</span> blocktype <span class="sc">*</span> distractortype <span class="sc">*</span> time_manipulation <span class="sc">+</span> <span class="fu">Error</span>(unique_identifier), <span class="at">data =</span> filtered.data_plusanovagroups)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>testanova <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_rmanova)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">as.data.frame</span>(testanova[[<span class="st">"Error: unique_identifier"</span>]][[<span class="dv">1</span>]]), <span class="st">"html"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sum Sq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean Sq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">F value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">19876039</td>
<td style="text-align: right;">496901</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>


</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">as.data.frame</span>(testanova[[<span class="st">"Error: Within"</span>]][[<span class="dv">1</span>]]), <span class="st">"html"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sum Sq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean Sq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">F value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">blocktype</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3544.966</td>
<td style="text-align: right;">3544.966</td>
<td style="text-align: right;">0.0767959</td>
<td style="text-align: right;">0.7818919</td>
</tr>
<tr class="even">
<td style="text-align: left;">distractortype</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1592932.100</td>
<td style="text-align: right;">1592932.100</td>
<td style="text-align: right;">34.5082846</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">time_manipulation</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">8983625.221</td>
<td style="text-align: right;">8983625.221</td>
<td style="text-align: right;">194.6156374</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">blocktype:distractortype</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">290143.396</td>
<td style="text-align: right;">290143.396</td>
<td style="text-align: right;">6.2854850</td>
<td style="text-align: right;">0.0127397</td>
</tr>
<tr class="odd">
<td style="text-align: left;">blocktype:time_manipulation</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">17149.010</td>
<td style="text-align: right;">17149.010</td>
<td style="text-align: right;">0.3715054</td>
<td style="text-align: right;">0.5426791</td>
</tr>
<tr class="even">
<td style="text-align: left;">distractortype:time_manipulation</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">95353.058</td>
<td style="text-align: right;">95353.058</td>
<td style="text-align: right;">2.0656690</td>
<td style="text-align: right;">0.1517653</td>
</tr>
<tr class="odd">
<td style="text-align: left;">blocktype:distractortype:time_manipulation</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9820.460</td>
<td style="text-align: right;">9820.460</td>
<td style="text-align: right;">0.2127443</td>
<td style="text-align: right;">0.6449830</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">12925040.845</td>
<td style="text-align: right;">46160.860</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>


</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>emm_res <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(model_rmanova, <span class="sc">~</span> blocktype <span class="sc">*</span> distractortype <span class="sc">*</span> time_manipulation)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>posthoc_pairwisecomp_main <span class="ot">&lt;-</span> <span class="fu">pairs</span>(emm_res, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># clean posthocs, add contextual grouping variables, and regexp away default titlings.</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>df_posthoc_pairwisecomps_main <span class="ot">&lt;-</span> <span class="fu">summary</span>(posthoc_pairwisecomp_main)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>df_posthoc_pairwisecomps_main<span class="sc">$</span>p.value <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">sprintf</span>(<span class="st">"%.40f"</span>, df_posthoc_pairwisecomps_main<span class="sc">$</span>p.value))</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>df_posthoc_pairwisecomps_main<span class="sc">$</span>contrast <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"_target time_manipulation(</span><span class="sc">\\</span><span class="st">d+)"</span>, <span class="st">" @ </span><span class="sc">\\</span><span class="st">1ms"</span>, df_posthoc_pairwisecomps_main<span class="sc">$</span>contrast)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>df_posthoc_pairwisecomps_main <span class="ot">&lt;-</span> df_posthoc_pairwisecomps_main <span class="sc">%&gt;%</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">within_timewindow =</span> {</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>      time_left <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(<span class="fu">str_split_fixed</span>(contrast, <span class="st">" - "</span>, <span class="dv">2</span>)[, <span class="dv">1</span>], <span class="st">"</span><span class="sc">\\</span><span class="st">d+ms"</span>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>      time_right <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(<span class="fu">str_split_fixed</span>(contrast, <span class="st">" - "</span>, <span class="dv">2</span>)[, <span class="dv">2</span>], <span class="st">"</span><span class="sc">\\</span><span class="st">d+ms"</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>      time_left <span class="sc">==</span> time_right</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">within_stimuluscat =</span> {</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>      cat_left <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(<span class="fu">str_split_fixed</span>(contrast, <span class="st">" - "</span>, <span class="dv">2</span>)[, <span class="dv">1</span>], <span class="st">"^</span><span class="sc">\\</span><span class="st">w+"</span>)</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>      cat_right <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(<span class="fu">str_split_fixed</span>(contrast, <span class="st">" - "</span>, <span class="dv">2</span>)[, <span class="dv">2</span>], <span class="st">"^</span><span class="sc">\\</span><span class="st">w+"</span>)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>      <span class="fu">paste</span>(cat_left, <span class="fu">ifelse</span>(cat_left <span class="sc">==</span> cat_right, <span class="st">"TRUE"</span>, <span class="st">"FALSE"</span>))</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>dfscratch <span class="ot">&lt;-</span> df_posthoc_pairwisecomps_main <span class="sc">%&gt;%</span></span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(contrast <span class="sc">==</span> <span class="st">"Ontogenetic Nonthreat @ 800ms - Ontogenetic Threat @ 800ms"</span> <span class="sc">|</span></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>           contrast <span class="sc">==</span> <span class="st">"Ontogenetic Nonthreat @ 2500ms - Ontogenetic Threat @ 2500ms"</span> <span class="sc">|</span></span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>           contrast <span class="sc">==</span> <span class="st">"Phylogenetic Nonthreat @ 800ms - Phylogenetic Threat @ 800ms"</span> <span class="sc">|</span></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>           contrast <span class="sc">==</span> <span class="st">"Phylogenetic Nonthreat @ 2500ms - Phylogenetic Threat @ 2500ms"</span> </span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>             )<span class="sc">%&gt;%</span></span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"Comparison"</span> <span class="ot">=</span> contrast) <span class="sc">%&gt;%</span></span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"Estimate (ms)"</span> <span class="ot">=</span> <span class="fu">round</span>(estimate, <span class="dv">3</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"T-ratio"</span> <span class="ot">=</span> <span class="fu">round</span>(t.ratio, <span class="dv">3</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"P-value"</span> <span class="ot">=</span> <span class="fu">round</span>(p.value, <span class="dv">3</span>))</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a><span class="co">#re-label the super low p value </span></span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>dfscratch<span class="sc">$</span><span class="st">"P-value"</span> <span class="ot">&lt;-</span> <span class="fu">as.character</span>(dfscratch<span class="sc">$</span><span class="st">"P-value"</span>)</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>dfscratch[<span class="dv">4</span>, <span class="st">"P-value"</span>] <span class="ot">&lt;-</span> <span class="st">"&lt;0.001"</span></span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a><span class="co">#switch the second and third rows so phylos are together and ontos are together</span></span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a><span class="cf">switch</span> <span class="ot">&lt;-</span> dfscratch[<span class="dv">2</span>, ]</span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a>dfscratch[<span class="dv">2</span>, ] <span class="ot">&lt;-</span> dfscratch[<span class="dv">3</span>, ]</span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a>dfscratch[<span class="dv">3</span>, ] <span class="ot">&lt;-</span> <span class="cf">switch</span></span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a><span class="co">#rename the Comparisons </span></span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a>dfscratch <span class="ot">&lt;-</span> dfscratch <span class="sc">%&gt;%</span></span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Comparison =</span> <span class="fu">case_when</span>(</span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a>    Comparison <span class="sc">==</span> <span class="st">"Ontogenetic Nonthreat @ 800ms - Ontogenetic Threat @ 800ms"</span> <span class="sc">~</span> <span class="st">"Ontogenetic Nonthreat - Ontogenetic Threat (800 ms)"</span>,</span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a>    Comparison <span class="sc">==</span> <span class="st">"Ontogenetic Nonthreat @ 2500ms - Ontogenetic Threat @ 2500ms"</span> <span class="sc">~</span> <span class="st">"Ontogenetic Nonthreat - Ontogenetic Threat (2500 ms)"</span>,</span>
<span id="cb12-46"><a href="#cb12-46" aria-hidden="true" tabindex="-1"></a>    Comparison <span class="sc">==</span> <span class="st">"Phylogenetic Nonthreat @ 800ms - Phylogenetic Threat @ 800ms"</span> <span class="sc">~</span> <span class="st">"Phylogenetic Nonthreat - Phylogenetic Threat (800 ms)"</span>,</span>
<span id="cb12-47"><a href="#cb12-47" aria-hidden="true" tabindex="-1"></a>    Comparison <span class="sc">==</span> <span class="st">"Phylogenetic Nonthreat @ 2500ms - Phylogenetic Threat @ 2500ms"</span> <span class="sc">~</span> <span class="st">"Phylogenetic Nonthreat - Phylogenetic Threat (2500 ms)"</span></span>
<span id="cb12-48"><a href="#cb12-48" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb12-49"><a href="#cb12-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-50"><a href="#cb12-50" aria-hidden="true" tabindex="-1"></a><span class="co">#remove unwanted columns</span></span>
<span id="cb12-51"><a href="#cb12-51" aria-hidden="true" tabindex="-1"></a>dfscratch <span class="ot">&lt;-</span> dfscratch <span class="sc">%&gt;%</span></span>
<span id="cb12-52"><a href="#cb12-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"Comparison"</span>, <span class="st">"Estimate (ms)"</span>, <span class="st">"T-ratio"</span>, <span class="st">"P-value"</span>)</span>
<span id="cb12-53"><a href="#cb12-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-54"><a href="#cb12-54" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(dfscratch, <span class="st">"html"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-55"><a href="#cb12-55" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Comparison</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate (ms)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">T-ratio</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ontogenetic Nonthreat - Ontogenetic Threat (800 ms)</td>
<td style="text-align: right;">56.736</td>
<td style="text-align: right;">1.196</td>
<td style="text-align: left;">0.933</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ontogenetic Nonthreat - Ontogenetic Threat (2500 ms)</td>
<td style="text-align: right;">103.050</td>
<td style="text-align: right;">2.172</td>
<td style="text-align: left;">0.372</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Phylogenetic Nonthreat - Phylogenetic Threat (800 ms)</td>
<td style="text-align: right;">153.817</td>
<td style="text-align: right;">3.241</td>
<td style="text-align: left;">0.029</td>
</tr>
<tr class="even">
<td style="text-align: left;">Phylogenetic Nonthreat - Phylogenetic Threat (2500 ms)</td>
<td style="text-align: right;">243.905</td>
<td style="text-align: right;">5.140</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>While we did not pre-register post-hoc pairwise comparisons, we realized after data collection that these would be integral to our assessment of whether we replicated the crucial findings in Abado et al.&nbsp;(2023). They informed us of each individual interaction amongst the variables in the data, providing directionality and a measure of significance in each comparison. Using Tukey HSD as the test statistic in these comparisons, we found that participants’ average detection of spiders was about 243.91ms faster than of birds in the 2500ms time condition (SE=47.46, dF=280, <em>t</em>=5.140, <em>p</em>&lt;0.0001) and about 153.817ms faster in the 800ms time condition (SE=47.45, d<em>F</em>=280, <em>t</em>=3.242, <em>p</em>=0.0287). This suggests that, on average, participants detected phylogenetic threats faster than phylogenetic non-threats in both time conditions. These two effects were consistent with and of even greater effect sizes than Abado et al.’s finding of a 136.13ms faster reaction time to spiders than to birds (<em>p</em>&lt;0.001), although it is notable that the statistical significance of the effect in our 800ms condition was much less robust than the effect in our 2500ms condition or Abado et al.’s finding.</p>
<p>We did not find any statistically significant difference in average detection of guns and telephones in either time condition (for the 2500ms condition: <em>t</em>=2.1716, <em>p</em>=0.372; and the 800ms condition: <em>t</em>=1.1956, <em>p</em>=0.933; Abado et al.’s effect size unknown, <em>p</em>&gt;0.05). Also consistent with Abado et al.’s finding, this suggests that, on average, participants did not detect ontogenetic threats faster than ontogenetic non-threats. These findings tentatively both replicate Abado et al.&nbsp;and suggest that participants showed an attention bias towards phylogenetic threats even when the duration for which they saw a stimulus was not long enough for judgment processes to occur.</p>
<p>We also found that participants detected phylogenetic threats 152.44ms faster, on average, than ontogenetic non-threats in the 2500ms time condition (<em>t</em>=3.2125, <em>p</em>=0.0314), and that they detected ontogenetic threats 194.51ms faster, on average, than phylogenetic threats in the 2500ms time condition (<em>t</em>=4.099, <em>p</em>&lt;0.001). Neither of these findings, though, are relevant to the research question at hand, and Abado et al.&nbsp;did not discuss findings like these.</p>
</section>
<section id="bayesian-general-mixed-modeling-analyses" class="level3">
<h3 class="anchored" data-anchor-id="bayesian-general-mixed-modeling-analyses">Bayesian General Mixed Modeling Analyses</h3>
<p>We pre-registered that we would use Bayesian general mixed modeling to assess whether group-level differences in reaction time can be explained better by discrepant type than by presentation time. While we decided after data collection that such complex statistical analyses would be superfluous for the goals of this research, we nonetheless compared the relative likelihoods of each variable contributing to the total variance in reaction time by comparing two GMM (general mixed models)-based bayes-factor analyses. This allowed us to better contextualize the extent to which each factor explained population-wide variation in the reaction time of our experiment.</p>
<div class="cell" data-description="Uses a lognormal distribution for reaction time, and relatively sensible priors characterizing the sample space to determine the relative likelihood of various factors in explaining the individual variation in rt in the data.">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model terms are block type and distractor type (effects combined constitute all trial stimulus configurations) and random subject intercepts</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>bayes_model_1 <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  individual_subject_mean_rt <span class="sc">~</span> blocktype <span class="sc">+</span> distractortype <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> subject_id),</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> filtered.data_plusanovagroups,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">shifted_lognormal</span>(<span class="at">link =</span> <span class="st">"identity"</span>),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">prior =</span> <span class="fu">c</span>(</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_prior</span>(<span class="st">"normal(0,4)"</span>, <span class="at">class =</span> <span class="st">"b"</span>),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_prior</span>(<span class="st">"cauchy(0,2)"</span>, <span class="at">class =</span> <span class="st">"sd"</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">iter =</span> <span class="dv">4000</span>, <span class="at">warmup =</span> <span class="dv">1000</span>, </span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">04204883</span>,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">save_pars =</span> <span class="fu">save_pars</span>(<span class="at">all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="co"># model terms are time manipulation and random subject intercepts</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>bayes_model_2 <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  individual_subject_mean_rt <span class="sc">~</span> time_manipulation <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> subject_id),</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> filtered.data_plusanovagroups,</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">shifted_lognormal</span>(<span class="at">link =</span> <span class="st">"identity"</span>),</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">prior =</span> <span class="fu">c</span>(</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_prior</span>(<span class="st">"normal(0,4)"</span>, <span class="at">class =</span> <span class="st">"b"</span>),</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_prior</span>(<span class="st">"cauchy(0,2)"</span>, <span class="at">class =</span> <span class="st">"sd"</span>)</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">iter =</span> <span class="dv">4000</span>, <span class="at">warmup =</span> <span class="dv">1000</span>, </span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">04204883</span>,</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">save_pars =</span> <span class="fu">save_pars</span>(<span class="at">all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>comparison_1 <span class="ot">&lt;-</span> <span class="fu">bayes_factor</span>(bayes_model_1, bayes_model_2)</span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>comparison_2 <span class="ot">&lt;-</span> <span class="fu">bayes_factor</span>(bayes_model_2, bayes_model_1)</span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a>prior_posterior_threat_stimulustype <span class="ot">&lt;-</span> <span class="fu">pp_check</span>(bayes_model_1)</span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a>prior_posterior_timecheck <span class="ot">&lt;-</span> <span class="fu">pp_check</span>(bayes_model_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The first mixed model, which was ran and assembled using the <em>BRMS</em> package <span class="citation" data-cites="Buerkner2017">(see <a href="#ref-Buerkner2017" role="doc-biblioref">Bürkner 2017</a>)</span>, only included time manipulation and random subject intercepts, while the second added the two factors of stimulus origin type and discrepant type atop random subject intercepts to the analysis. Rather than assume a standard unit, we used a shifted lognormal distribution to best explain latent sampling variation in reaction time tasks. This distribution is often regarded as a better fit for real world distributions of reaction time data than traditional normality-assumptive priors <span class="citation" data-cites="Wagenmakers2007">Rouder (<a href="#ref-Rouder2005" role="doc-biblioref">2005</a>)</span> Per the prior and posterior estimates given in Figure 6 and Figure 7, this shape fit the observed distribution of our reaction time data quite well, suggesting that the shifted lognormal distribution was an appropriate choice.</p>
<div class="cell" data-description="Recolors and standardizes appearance of default bayesplot mappings for prior-posterior odds evaluation. Also labels things a bit more clearly unit-wise.">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#"Pretty Pictures II: Recolor and Clarify pp_check"</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>alttc <span class="ot">&lt;-</span> prior_posterior_timecheck <span class="sc">+</span> <span class="fu">theme_fivethirtyeight</span>(<span class="at">base_size =</span> <span class="dv">6</span>, <span class="at">base_family =</span> <span class="st">"Ubuntu"</span>) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Prior x Posterior Odds (Time Manipulation w/ random subject effects)"</span>) <span class="sc">+</span>  <span class="fu">theme</span>(<span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">9</span>),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="dv">20</span>, <span class="dv">20</span>, <span class="st">"pt"</span>)),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>)) <span class="sc">+</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"cumulative proportion of total"</span>) <span class="sc">+</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"reaction time (ms)"</span>) <span class="sc">+</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_paletteer_d</span>(<span class="st">"NineteenEightyR::cobra"</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'observed data'</span>, <span class="st">'modeled'</span>))</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>altst <span class="ot">&lt;-</span> prior_posterior_threat_stimulustype <span class="sc">+</span> <span class="fu">theme_fivethirtyeight</span>(<span class="at">base_size =</span> <span class="dv">6</span>, <span class="at">base_family =</span> <span class="st">"Ubuntu"</span>) <span class="sc">+</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Prior x Posterior Odds (Stimulus Origin x Discrepant Type w/ random subject effects)"</span>) <span class="sc">+</span>  <span class="fu">theme</span>(<span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">9</span>),</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="dv">20</span>, <span class="dv">20</span>, <span class="st">"pt"</span>)),</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">color =</span> <span class="cn">NA</span>)) <span class="sc">+</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"cumulative proportion of total"</span>) <span class="sc">+</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"reaction time (ms)"</span>) <span class="sc">+</span></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_paletteer_d</span>(<span class="st">"beyonce::X101"</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'observed data'</span>, <span class="st">'modeled'</span>))</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(alttc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-alttc" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-alttc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="SG-Analysis_darkmode_files/figure-html/fig-alttc-1.svg" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-alttc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Prior-posterior checks for time manipulation with random subject effects on reaction time. A sample of 50 Markov Chain Monte Carlo runs beneath the observed distribution.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-description="Recolors and standardizes appearance of default bayesplot mappings for prior-posterior odds evaluation. Also labels things a bit more clearly unit-wise.">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(altst)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-altst" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-altst-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="SG-Analysis_darkmode_files/figure-html/fig-altst-1.svg" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-altst-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Prior-posterior checks for origin type and discrepant type interaction with random subject effects on reaction time. A sample of 50 Markov Chain Monte Carlo runs beneath the observed distribution.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Because we did not have any prior expectations about directional changes in the parameter space that result from a true effect of any of the variables under study, we set a prior distribution of population wide effects centered on zero for the population-wide regression coefficients in our model, and assumed that the effects would impact reaction time in a normal fashion. However, since we could not be certain that this assumption was appropriate, we used a moderately conservative estimate of standard deviations (four) from the mean before we could term the impact of an independent variable on the distribution of regression coefficients as informative. For the same reason, we also used an uninformed Cauchy prior, centered on 0 with a <span class="math inline">\(\gamma\)</span> of 2 (which has meaningfully fatter tails than one with <span class="math inline">\(\gamma\)</span> 1) as the assumed parameter space for the standard deviations of true effects. With these models ran, the overall pattern was even more apparent than before: the relative likelihood of the time-manipulation model explaining the group-level patterns in reaction time over the stimulus origin and discrepant object type model, under these conditions, yielded a <em>BF</em> &gt; 1.59*10^30. This suggests that, on the whole, any impact of the origin type of a stimulus or the discrepant type in the stimulus on reaction time was negligible.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>By conducting this study, we aimed to replicate the attention bias toward phylogenetic threats but not toward ontogenetic threats that Abado et al.&nbsp;(2023) observed. We also aimed to assess whether judgment, rather than just perception, plays a role in this effect. Towards this end, we looked at the differences in participant response times to stimuli when the stimuli contained threatening and non-threatening, phylogenetic and ontogenetic images. To assess the role of judgment processes, we performed these analyses with two presentation times of stimuli.</p>
<p>Because our <em>RMANOVA</em> and pairwise comparisons found significant reaction time differences in the predicted directions, the data support Abado et al.’s attentional bias finding. Our observed effects were not as large nor as statistically significant as Abado et al.’s findings, but they were significant nonetheless. Thus, this study successfully replicated the findings of Abado et al., providing tentative evidence that U.S. adults indeed exhibit an attentional bias toward phylogenetic threats but not toward ontogenetic threats. Importantly, our results suggest that this bias may be driven by perceptual processes rather than judgment processes.</p>
<section id="limitations-and-future-research" class="level3">
<h3 class="anchored" data-anchor-id="limitations-and-future-research">Limitations and Future Research</h3>
<p>Though these significant findings were found through careful recreation of the methodology of Abado et al., they should be interpreted with caution due to our smaller effect sizes and less robust significance in the shorter time condition. Additionally, our reduced sample size may have restricted the power of our study, and our oversight in excluding participants with histories of neurological disorders or ADHD may have introduced more variability in our data.</p>
<p>To ensure that the results of this study and Abado et al.’s study are generalizable to all phylogenetic and ontogenetic threats, future research should involve images of different items to verify that the observed effects are not specific to spiders, birds, butterflies, guns, telephones, and staplers.</p>
<p>To continue investigation of whether this attention bias is a top-down effect, future researchers could use EEG technology during this visual discrimination task to directly record brain activity. This would allow researchers to better understand when the attention bias occurs in perceptual processes or afterwards. Also, conducting cross-cultural comparisons could shed light on how perceptual processes, including threat detection, vary across different cultural backgrounds. Such studies could help strengthen the universality of the findings, as cultural factors might influence responses to the same visual stimuli.</p>
<p>In total, this study tentatively replicated Abado et al.’s (2023) attention bias finding, suggesting that U.S. adults show an attention bias toward phylogenetic threats but not toward ontogenetic threats. Moreover, this study also suggests that this attention bias is not a result of judgment processes and, therefore, is potentially occurring at the perceptual level. Future research could significantly advance our understanding of the mechanisms underlying visual discrimination, providing more robust and generalizable findings.</p>
</section>
</section>
<section id="author-contributions" class="level2">
<h2 class="anchored" data-anchor-id="author-contributions">Author Contributions</h2>
<p>All authors conceived of and developed the hypotheses and experiment design. M.F. wrote the experimental script and programmed the study. L.O. and J.H.A. sourced the stimuli images and L.O. connected the DataPipe to the study’s OSF page. J.H.A., Z.C., and J.A. pre-registered the experiment and obtained IRB exemption approval. L.O., Z.C., J.H.A., and J.L. made the experiment available to Prolific users. M.F. contributed most significantly to statistical analysis, with J.H.A., Z.C., and L.O. also contributing. M.F. and J.H.A. contributed to data visualization and quarto proofing. M.F., L.O., Z.C., and J.H.A., as well as several other Vassar College students piloted the experiment. J.H.A., M.F., L.O., and Z.C. contributed to initial drafting of this report. J.H.A facilitated editing and revising, with M.F., L.O., and Z.F. also contributing.</p>
</section>
<section id="funding" class="level2">
<h2 class="anchored" data-anchor-id="funding">Funding</h2>
<p>This work was funded by the Vassar College Cognitive Science department, as we conducted this study for an assignment in our COGS219 Research Methods in Cognitive Science class.</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Abado2023" class="csl-entry" role="listitem">
Abado, Elinor, Tatjana Aue, and Hadas Okon-Singer. 2023. <span>“Spider Vs. Guns: Expectancy and Attention Biases to Phylogenetic Threat Do Not Extend to Ontogenetic Threat.”</span> <em>Frontiers in Psychology</em> 14 (August). <a href="https://doi.org/10.3389/fpsyg.2023.1232985">https://doi.org/10.3389/fpsyg.2023.1232985</a>.
</div>
<div id="ref-Buerkner2017" class="csl-entry" role="listitem">
Bürkner, Paul-Christian. 2017. <span>“Brms: An r Package for Bayesian Multilevel Models Using Stan.”</span> <em>Journal of Statistical Software</em> 80 (1). <a href="https://doi.org/10.18637/jss.v080.i01">https://doi.org/10.18637/jss.v080.i01</a>.
</div>
<div id="ref-Firestone2015" class="csl-entry" role="listitem">
Firestone, Chaz, and Brian J. Scholl. 2015. <span>“Cognition Does Not Affect Perception: Evaluating the Evidence for <span>‘Top-down’</span> Effects.”</span> <em>Behavioral and Brain Sciences</em> 39 (July). <a href="https://doi.org/10.1017/s0140525x15000965">https://doi.org/10.1017/s0140525x15000965</a>.
</div>
<div id="ref-Hugdahl1989" class="csl-entry" role="listitem">
Hugdahl, Kenneth, and Bjørn Helge Johnsen. 1989. <span>“Preparedness and Electrodermal Fear-Conditioning: Ontogenetic Vs Phylogenetic Explanations.”</span> <em>Behaviour Research and Therapy</em> 27 (3): 269–78. <a href="https://doi.org/10.1016/0005-7967(89)90046-6">https://doi.org/10.1016/0005-7967(89)90046-6</a>.
</div>
<div id="ref-Leeuw2023" class="csl-entry" role="listitem">
Leeuw, Joshua R. de, Rebecca A. Gilbert, and Björn Luchterhandt. 2023. <span>“jsPsych: Enabling an Open-Source Collaborative Ecosystem of Behavioral Experiments.”</span> <em>Journal of Open Source Software</em> 8 (85): 5351. <a href="https://doi.org/10.21105/joss.05351">https://doi.org/10.21105/joss.05351</a>.
</div>
<div id="ref-Parsons2021" class="csl-entry" role="listitem">
Parsons, Sam. 2021. <span>“Splithalf: Robust Estimates of Split Half Reliability.”</span> <em>Journal of Open Source Software</em> 6 (60): 3041. <a href="https://doi.org/10.21105/joss.03041">https://doi.org/10.21105/joss.03041</a>.
</div>
<div id="ref-RCT2024" class="csl-entry" role="listitem">
R Core Team. 2024. <em>R: A Language and Environment for Statistical Computing</em>. Vienna, Austria: R Foundation for Statistical Computing.
</div>
<div id="ref-Rouder2005" class="csl-entry" role="listitem">
Rouder, Jeffrey N. 2005. <span>“Are Unshifted Distributional Models Appropriate for Response Time?”</span> <em>Psychometrika</em> 70 (2): 377–81. <a href="https://doi.org/10.1007/s11336-005-1297-7">https://doi.org/10.1007/s11336-005-1297-7</a>.
</div>
<div id="ref-Seligman1971" class="csl-entry" role="listitem">
Seligman, Martin E. P. 1971. <span>“Phobias and Preparedness.”</span> <em>Behavior Therapy</em> 2 (3): 307–20. <a href="https://doi.org/10.1016/s0005-7894(71)80064-3">https://doi.org/10.1016/s0005-7894(71)80064-3</a>.
</div>
<div id="ref-Wagenmakers2007" class="csl-entry" role="listitem">
Wagenmakers, Eric-Jan, and Scott Brown. 2007. <span>“On the Linear Relation Between the Mean and the Standard Deviation of a Response Time Distribution.”</span> <em>Psychological Review</em> 114 (3): 830–41. <a href="https://doi.org/10.1037/0033-295x.114.3.830">https://doi.org/10.1037/0033-295x.114.3.830</a>.
</div>
<div id="ref-Wickham2019" class="csl-entry" role="listitem">
Wickham, Hadley, Mara Averick, Jennifer Bryan, Winston Chang, Lucy McGowan, Romain François, Garrett Grolemund, et al. 2019. <span>“Welcome to the Tidyverse.”</span> <em>Journal of Open Source Software</em> 4 (43): 1686. <a href="https://doi.org/10.21105/joss.01686">https://doi.org/10.21105/joss.01686</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>