name: Quarto via Nix

on:
  workflow_dispatch:
  push:
    paths:
      - '**.qmd'
      - '**.bib'
      - '**.csl'
      - '**.scss'
      - '**.css'
      - '**.js'
      - '**.jpeg'
      - '**.svg'
      - 'flake.nix'
      - 'flake.lock'
      
  pull_request:
    paths:
      - '**.qmd'
      - '**.bib'
      - '**.csl'
      - '**.scss'
      - '**.css'
      - '**.js'
      - '**.jpeg'
      - '**.svg'
      - 'flake.nix'
      - 'flake.lock'

permissions:
  contents: write
  packages: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
            
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Enable Nix magic cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build documents
        run: |
          nix flake check
          nix build \
            --show-trace \
            --verbose
          mkdir -p artifacts
          cp -r result/* artifacts/
          
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: documents-and-logs
          path: artifacts/

  create-release:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Timestamp
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: documents-and-logs
          path: artifacts

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.sha }}-${{ steps.date.outputs.date }}
          name: Release ${{ github.sha }} - ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
          files: artifacts/*
          generate_release_notes: true